# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TWEB
description: > # this means to ignore newlines until "baseurl:"
  The Bootcamp lab
contactTitle: Get in touch
contactDescription: Have a question ? A problem with our application ? Just contact us :)
baseurl: "/HeigVD-TWEB-Bootcamp" # the subpath of your site, e.g. /blog
url: "https://cotzadev.github.io" # the base hostname & protocol for your site
copyright: Heig-VD
# Contact info
email: andrea.cotza@yopmail.com
mailingAddress: Heig-VD<br />Route de Cheseaux 1<br />CP 521<br />CH-1401 Yverdon-les-Bains
phone: +41 (0)24 557 63 30
# Build settings
markdown: kramdown
